"""Fix column name emial

Revision ID: 20c55c29d604
Revises: 812c1fd7202b
Create Date: 2025-06-23 13:42:19.040587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20c55c29d604'
down_revision = '812c1fd7202b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=60), nullable=False))
        batch_op.create_unique_constraint('uq_clients_email', ['email'])
        batch_op.drop_column('emial')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emial', sa.VARCHAR(length=60), nullable=False))
        batch_op.drop_constraint('uq_clients_email', type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
