"""Change start_time to start_date

Revision ID: 812c1fd7202b
Revises: 2e802a6643ae
Create Date: 2025-06-20 17:46:34.880066

"""
from alembic import op
import sqlalchemy as sa
from datetime import date


# revision identifiers, used by Alembic.
revision = '812c1fd7202b'
down_revision = '2e802a6643ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        # Add column with default value first
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=True, server_default=sa.text('CURRENT_DATE')))
        
    # Update existing records with a default date
    op.execute("UPDATE orders SET start_date = CURRENT_DATE WHERE start_date IS NULL")
    
    with op.batch_alter_table('orders', schema=None) as batch_op:
        # Now make it NOT NULL
        batch_op.alter_column('start_date', nullable=False, server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('start_date')

    # ### end Alembic commands ###
