"""Add columns Address and Company to Client table

Revision ID: ddfee77254d7
Revises: 9ae7aa5f90bc
Create Date: 2025-07-11 10:14:44.602928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddfee77254d7'
down_revision = '9ae7aa5f90bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('address')
        batch_op.drop_column('company')

    # ### end Alembic commands ###
